<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class ModelosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('modelos')->insert([
            [
                'name' => 'Andressa Viena',
                'image' => 'assets/images/modelos_eclat/andressa.jpg',
                'altura' => 1.85,
                'bust' => 85,
                'cintura' => 60,
                'zapato' => 35,
                'vestido' => 36,
                'tamano' => 'M',
                'ojos' => 'Negros',
                'cabello' => 'Negro',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1997')->format('Y-m-d'),
                'ubicacion' => 'Buenos Aires, Capital Federal, Argentina',
                'description' => 'Elegância contemporânea com beleza clássica. Pele impecável, traços finos e olhar confiante. Ideal para campanhas de beleza de luxo, maquiagem e editoriais sofisticados.',
                'estilos' => json_encode([
                    'Estilo' => 'Elegância atemporal, refinada e poderosa.',
                    'Trazos marcantes' => 'Pele luminosa impecável, olhos expressivos, lábios definidos, rosto harmônico.',
                    'Personalidad que transmite' => 'Confiança, sofisticação e magnetismo.',
                    'Campañas de destaque' => 'Beleza de luxo, skincare premium, maquiagem de alta moda, joalheria e editoriais de moda conceitual.',
                    'Fuerza visual' => 'Capacidade de sustentar closes intensos com impacto imediato.',
                    ])
            ],
            [
                'name' => 'Juan Díaz',
                'image' => 'assets/images/modelos_eclat/juan.jpg',
                'altura' => 1.85,
                'bust' => 90,
                'cintura' => 75,
                'zapato' => 40,
                'vestido' => 47,
                'tamano' => 'G',
                'ojos' => 'Verde Oliva',
                'cabello' => 'Castaño Oscuro',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '29/09/1999')->format('Y-m-d'),
                'ubicacion' => 'Rawson, Chubut, Argentina',
                'description' => 'Perfil sério, presença magnética e postura refinada. Combina perfeitamente com moda masculina premium, ternos, campanhas de lifestyle urbano e editoriais cosmopolitas.',
                'estilos' => json_encode([
                    'Estilo' => 'Urbano, sofisticado e versátil.',
                    'Trazos marcantes' => 'Linha do maxilar definida, barba sutil, porte atlético, olhar contemplativo.',
                    'Personalidad que transmite' => 'Determinação, charme discreto e inteligência.',
                    'Campañas de destaque' => 'Moda masculina premium, ternos, alfaiataria, campanhas de relógios e lifestyle urbano sofisticado.',
                    'Fuerza visual' => 'Perfeito para representar o homem cosmopolita, focado e contemporâneo.',
                    ])
            ],
            [
                'name' => 'Paula Olegari',
                'image' => 'assets/images/modelos_eclat/paula.jpg',
                'altura' => 1.78,
                'bust' => 85,
                'cintura' => 60,
                'zapato' => 39,
                'vestido' => 36,
                'tamano' => 'M',
                'ojos' => 'Ambar',
                'cabello' => 'Rubio Oscuro',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '24/02/1998')->format('Y-m-d'),
                'ubicacion' => 'Rosario, Santa Fe, Argentina',
                'description' => 'Postura delicada, expressão introspectiva e estilo clean. Representa autenticidade e leveza, excelente para editoriais minimalistas, marcas de moda sustentável e campanhas intimistas.',
                'estilos' => json_encode([
                    'Estilo' => 'Minimalista, introspectiva e autêntica.',
                    'Trazos marcantes' => 'Cabelos cacheados soltos, pele clara natural, silhueta elegante.',
                    'Personalidad que transmite' => 'Delicadeza, autenticidade e introspecção.',
                    'Campañas de destaque' => 'Moda sustentável, editoriais de lifestyle clean, marcas conceituais, beleza natural.',
                    'Fuerza visual' => 'Capacidade de transmitir pureza e autenticidade em ambientes simples ou editoriais intimistas.',
                ]),
            ],
            [
                'name' => 'Lucas Fernandez',
                'image' => 'assets/images/modelos_eclat/lucas.jpg',
                'ojos' => 'Negros',
                'altura' => 1.88,
                'bust' => 95,
                'cintura' => 75,
                'zapato' => 42,
                'vestido' => 0, // não aplicável em homem, pode deixar 0 ou null
                'tamano' => "P",
                'cabello' => 'Castaño',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '20/10/2000')->format('Y-m-d'),
                'ubicacion' => 'Córdoba, Córdoba, Argentina',
                'description' => 'Atitude descolada, visual streetwear e presença cool. Ótimo para campanhas jovens, moda alternativa, editoriais de street style e publicidade voltada ao público criativo.',
                'estilos' => json_encode([
                    'Estilo' => 'Streetwear, rebelde e criativo.',
                    'Trazos marcantes' => 'Postura despojada, cabelo volumoso, óculos futuristas, atitude cool.',
                    'Personalidad que transmite' => 'Liberdade, ousadia e vanguarda.',
                    'Campañas de destaque' => 'Moda urbana, editoriais de tendências jovens, street style, marcas alternativas e campanhas digitais.',
                    'Fuerza visual' => 'Representa o jovem contemporâneo, irreverente e conectado com a cultura pop.',
                ]),
            ],
            [
                'name' => 'Victoria Bithencurt',
                'image' => 'assets/images/modelos_eclat/victoria.jpg',
                'altura' => 1.80,
                'bust' => 87,
                'cintura' => 62,
                'zapato' => 38,
                'vestido' => 36,
                'tamano' => "P",
                'ojos' => 'Verdes',
                'cabello' => 'Pelirroja',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '14/11/1996')->format('Y-m-d'),
                'ubicacion' => 'Olivos, Buenos Aires, Argentina',
                'description' => 'Olhar doce, sorriso suave e carisma natural. A estética leve e colorida combina com campanhas de moda feminina, verão, lifestyle tropical e beleza natural.',
                'estilos' => json_encode([
                    'Estilo' => 'Feminino, carismático e natural.',
                    'Trazos marcantes' => 'Cabelos longos ruivos, olhos claros, sorriso sutil, pele radiante.',
                    'Personalidad que transmite' => 'Alegria, calor humano e proximidade.',
                    'Campañas de destaque' => 'Moda feminina colorida, lifestyle tropical, campanhas de verão, cosméticos e moda casual.',
                    'Fuerza visual' => 'Brilho natural que conecta facilmente com o público, passando frescor e acessibilidade.',
                ]),
            ],
            [
                'name' => 'Francisco Gómez',
                'image' => 'assets/images/modelos_eclat/francisco.jpg',
                'altura' => 1.80,
                'bust' => 100,
                'cintura' => 78,
                'zapato' => 43,
                'vestido' => 0, // idem Lucas
                'tamano' => "M",
                'ojos' => 'Ambar',
                'cabello' => 'Negros',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1998')->format('Y-m-d'),
                'ubicacion' => 'Neuquén, Neuquén, Argentina',
                'description' => 'Traços fortes, olhar profundo e presença dramática. Excelente para editoriais de moda em preto e branco, campanhas conceituais, moda alternativa e publicidade de impacto artístico.',
                'estilos' => json_encode([
                    'Estilo' => 'Dramático, sofisticado e conceitual.',
                    'Trazos marcantes' => 'Cabelos ondulados, olhar penetrante, presença forte em preto e branco.',
                    'Personalidad que transmite' => 'Intensidade, mistério e profundidade artística.',
                    'Campañas de destaque' => 'Editorial conceitual, moda alternativa, campanhas de alta costura, publicidade artística.',
                    'Fuerza visual' => 'Ideal para marcas que buscam expressividade dramática e imagens memoráveis.',
                ]),
            ],
            [
                'name' => 'Valentina Rossì',
                'image' => 'assets/images/modelos_eclat/valentina.jpg',
                'altura' => 1.75,
                'bust' => 86,
                'cintura' => 62,
                'zapato' => 38,
                'vestido' => 36,
                'tamano' => "M",
                'ojos' => 'Castaños Claros',
                'cabello' => 'Castaños',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1997')->format('Y-m-d'),
                'ubicacion' => 'Rosario, Santa Fe, Argentina',
                'description' => 'Traços fortes, olhar profundo e presença dramática. Excelente para editoriais de moda em preto e branco, campanhas conceituais, moda alternativa e publicidade de impacto artístico.',
                'estilos' => json_encode([
                    'Estilo' => 'Glamouroso, elegante y sofisticado, con un aire de red carpet.',
                    'Trazos marcantes' => 'Líneas fluidas, corte asimétrico con abertura lateral que resalta movimiento y feminidad.',
                    'Personalidad que transmite' => 'Confianza, sensualidad discreta y poder femenino.',
                    'Campañas de destaque' => 'Moda de lujo, editoriales de alta costura, marcas premium de gala.',
                    'Fuerza visual' => 'Impacta por el brillo y dramatismo del vestido en contraste con la pose dinámica.',
                ]),
            ],
            [
                'name' => 'Jose Bianchi',
                'image' => 'assets/images/modelos_eclat/jose.jpg',
                'altura' => 1.90,
                'bust' => 100,
                'cintura' => 80,
                'zapato' => 44,
                'vestido' => 0,
                'tamano' => "G",
                'ojos' => 'Morones',
                'cabello' => 'Castaño Oscuro',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1996')->format('Y-m-d'),
                'ubicacion' => 'Buenos Aires, Capital Federal, Argentina',
                'description' => 'Traços fortes, olhar profundo e presença dramática. Excelente para editoriais de moda em preto e branco, campanhas conceituais, moda alternativa e publicidade de impacto artístico.',
                'estilos' => json_encode([
                    'Estilo' => 'Casual clásico con un giro moderno.',
                    'Trazos marcantes' => 'Estilo atemporal, sonrisa fresca y natural.',
                    'Personalidad que transmite' => 'Cercanía, autenticidad y optimismo juvenil.',
                    'Campañas de destaque' => 'Moda urbana, lifestyle, marcas de ropa masculina y fragancias.',
                    'Fuerza visual' => 'Su expresión abierta y espontánea genera conexión inmediata.',
                ]),
            ],
            [
                'name' => 'Camila Sánchez',
                'image' => 'assets/images/modelos_eclat/camila.jpg',
                'altura' => 1.80,
                'bust' => 88,
                'cintura' => 63,
                'zapato' => 39,
                'vestido' => 38,
                'tamano' => "M",
                'ojos' => 'Negros',
                'cabello' => 'Negros',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1995')->format('Y-m-d'),
                'ubicacion' => 'Bahía Blanca, Buenos Aires, Argentina',
                'description' => 'Traços fortes, olhar profundo e presença dramática. Excelente para editoriais de moda em preto e branco, campanhas conceituais, moda alternativa e publicidade de impacto artístico.',
                'estilos' => json_encode([
                    'Estilo' => 'Audaz, salvaje y sofisticado.',
                    'Trazos marcantes' => 'Mirada cálida y fuerte, cuerpo marcante y simple, postura elegante.',
                    'Personalidad que transmite' => 'Valentía, seguridad y magnetismo.',
                    'Campañas de destaque' => 'Alta moda, editoriales de lujo, marcas con actitud irreverente.',
                    'Fuerza visual' => 'La intensidad del animal print enmarcado por el fondo natural potencia la fuerza de su mirada.',
                ]),
            ],
            [
                'name' => 'Dylan Rodríguez',
                'image' => 'assets/images/modelos_eclat/dylan.jpg',
                'altura' => 1.95,
                'bust' => 105,
                'cintura' => 82,
                'zapato' => 45,
                'vestido' => 0,
                'tamano' => "M",
                'ojos' => 'Negros',
                'cabello' => 'Negros',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1996')->format('Y-m-d'),
                'ubicacion' => 'Buenos Aires, Capital Federal, Argentina',
                'description' => 'Traços fortes, olhar profundo e presença dramática. Excelente para editoriais de moda em preto e branco, campanhas conceituais, moda alternativa e publicidad de impacto artístico.',
                'estilos' => json_encode([
                    'Estilo' => 'Minimalista y urbano, con influencia streetwear.',
                    'Trazos marcantes' => 'Silueta amplia, monocromía, actitud relajada.',
                    'Personalidad que transmite' => 'Frescura, modernidad y un aire introspectivo.',
                    'Campañas de destaque' => 'Moda urbana, colecciones cápsula de streetwear, marcas sostenibles.',
                    'Fuerza visual' => 'La pureza del look monocromático transmite calma y sofisticación.',
                ]),
            ],
            [
                'name' => 'Sofia Ricci',
                'image' => 'assets/images/modelos_eclat/sofia.jpg',
                'altura' => 1.90,
                'bust' => 90,
                'cintura' => 65,
                'zapato' => 40,
                'vestido' => 38,
                'tamano' => "P",
                'ojos' => 'Azules',
                'cabello' => 'Rubio',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1994')->format('Y-m-d'),
                'ubicacion' => 'Mendoza, Mendoza, Argentina',
                'description' => 'Traços fortes, olhar profundo e presença dramática. Excelente para editoriais de moda em preto e branco, campanhas conceituais, moda alternativa e publicidad de impacto artístico.',
                'estilos' => json_encode([
                    'Estilo' => 'Haute couture, teatral y etéreo.',
                    'Trazos marcantes' => 'Cuerpo en formato escultural intenso, miradas marcantes, actitud fuerte y determinada.',
                    'Personalidad que transmite' => 'Misticismo, audacia artística y magnetismo escénico.',
                    'Campañas de destaque' => 'Pasarelas de alta moda, editoriales conceptuales, marcas exclusivas.',
                    'Fuerza visual' => 'El dramatismo del diseño junto al gesto coreográfico la convierten en un ícono visual.',
                ]),
            ],
            [
                'name' => 'Emanuel Hernández',
                'image' => 'assets/images/modelos_eclat/emanuel.jpg',
                'altura' => 1.85,
                'bust' => 102,
                'cintura' => 80,
                'zapato' => 43,
                'vestido' => 0,
                'tamano' => "M",
                'ojos' => 'Negros',
                'cabello' => 'Rubio',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1997')->format('Y-m-d'),
                'ubicacion' => 'Quilmes, Buenos Aires, Argentina',
                'description' => 'Traços fortes, olhar profundo e presença dramática. Excelente para editoriais de moda em preto e branco, campañas conceptuales, moda alternativa y publicidad de impacto artístico.',
                'estilos' => json_encode([
                    'Estilo' => 'Alternativo, artístico y rebelde.',
                    'Trazos marcantes' => 'Mirada intensa, tatuaje visible, estética en blanco y negro que realza fuerza emocional.',
                    'Personalidad que transmite' => 'Profundidad, misterio y un aire provocador.',
                    'Campañas de destaque' => 'Moda alternativa, campañas de joyería, marcas de identidad fuerte.',
                    'Fuerza visual' => 'Su expresión desafiante y el contraste en blanco y negro generan una narrativa poderosa.',
                ]),
            ]
        ]);
    }
}
