<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class ModelosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('modelos')->insert([
            [
                'name' => 'Andressa Viena',
                'image' => 'assets/images/modelos_eclat/andressa.jpg',
                'altura' => 1.85,
                'bust' => 85,
                'cintura' => 60,
                'zapato' => 35,
                'vestido' => 36,
                'tamano' => 'M',
                'ojos' => 'Negros',
                'cabello' => 'Negro',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1997')->format('Y-m-d'),
                'ubicacion' => 'Buenos Aires, Capital Federal, Argentina',
                'instagram' => 'andressa_oficial',
                'description' => 'Elegância contemporânea com beleza clássica. Pele impecável, traços finos e olhar confiante. Ideal para campanhas de beleza de luxo, maquiagem e editoriais sofisticados. Pele luminosa impecável, olhos expressivos, lábios definidos, rosto harmônico. Confiança, sofisticação e magnetismo. Capacidade de sustentar closes intensos com impacto imediato.',
                'campana' => 'Beleza de luxo, skincare premium, maquiagem de alta moda, joalheria e editoriais de moda conceitual.',
            ],
            [
                'name' => 'Juan Díaz',
                'image' => 'assets/images/modelos_eclat/juan.jpg',
                'altura' => 1.85,
                'bust' => 90,
                'cintura' => 75,
                'zapato' => 40,
                'vestido' => 47,
                'tamano' => 'G',
                'ojos' => 'Verde Oliva',
                'cabello' => 'Castaño Oscuro',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '29/09/1999')->format('Y-m-d'),
                'ubicacion' => 'Rawson, Chubut, Argentina',
                'instagram' => 'diazjuani',
                'description' => 'Perfil sério, presença magnética e postura refinada. Combina perfeitamente com moda masculina premium, ternos, campanhas de lifestyle urbano e editoriais cosmopolitas. Linha do maxilar definida, barba sutil, porte atlético, olhar contemplativo. Determinação, charme discreto e inteligência. Perfeito para representar o homem cosmopolita, focado e contemporâneo.',
                'campana' => 'Moda masculina premium, ternos, alfaiataria, campanhas de relógios e lifestyle urbano sofisticado.',
            ],
            [
                'name' => 'Paula Olegari',
                'image' => 'assets/images/modelos_eclat/paula.jpg',
                'altura' => 1.78,
                'bust' => 85,
                'cintura' => 60,
                'zapato' => 39,
                'vestido' => 36,
                'tamano' => 'M',
                'ojos' => 'Ambar',
                'cabello' => 'Rubio Oscuro',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '24/02/1998')->format('Y-m-d'),
                'ubicacion' => 'Rosario, Santa Fe, Argentina',
                'instagram' => 'imolegari',
                'description' => 'Postura delicada, expressão introspectiva e estilo clean. Representa autenticidade e leveza, excelente para editoriais minimalistas, marcas de moda sustentável e campanhas intimistas. Cabelos cacheados soltos, pele clara natural, silhueta elegante. Delicadeza, autenticidade e introspecção. Capacidade de transmitir pureza e autenticidade em ambientes simples ou editoriais intimistas.',
                'campana' =>  'Moda sustentável, editoriais de lifestyle clean, marcas conceituais, beleza natural.',
            ],
            [
                'name' => 'Lucas Fernandez',
                'image' => 'assets/images/modelos_eclat/lucas.jpg',
                'ojos' => 'Negros',
                'altura' => 1.88,
                'bust' => 95,
                'cintura' => 75,
                'zapato' => 42,
                'vestido' => 0, // não aplicável em homem, pode deixar 0 ou null
                'tamano' => "P",
                'cabello' => 'Castaño',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '20/10/2000')->format('Y-m-d'),
                'ubicacion' => 'Córdoba, Córdoba, Argentina',
                'instagram' => 'feerr_luc',
                'description' => 'Atitude descolada, visual streetwear e presença cool. Ótimo para campanhas jovens, moda alternativa, editoriais de street style e publicidade voltada ao público criativo. Postura despojada, cabelo volumoso, óculos futuristas, atitude cool. Liberdade, ousadia e vanguarda. Representa o jovem contemporâneo, irreverente e conectado com a cultura pop.',
                'campana' => 'Moda urbana, editoriais de tendências jovens, street style, marcas alternativas e campanhas digitais.',
            ],
            [
                'name' => 'Victoria Bithencurt',
                'image' => 'assets/images/modelos_eclat/victoria.jpg',
                'altura' => 1.80,
                'bust' => 87,
                'cintura' => 62,
                'zapato' => 38,
                'vestido' => 36,
                'tamano' => "P",
                'ojos' => 'Verdes',
                'cabello' => 'Pelirroja',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '14/11/1996')->format('Y-m-d'),
                'ubicacion' => 'Olivos, Buenos Aires, Argentina',
                'instagram' => 'vic_bithencurt',
                'description' => 'Olhar doce, sorriso suave e carisma natural. A estética leve e colorida combina com campanhas de moda feminina, verão, lifestyle tropical e beleza natural. Cabelos longos ruivos, olhos claros, sorriso sutil, pele radiante. Alegria, calor humano e proximidade. Brilho natural que conecta facilmente com o público, passando frescor e acessibilidade.',
                'campana' => 'Moda feminina colorida, lifestyle tropical, campanhas de verão, cosméticos e moda casual.',
            ],
            [
                'name' => 'Francisco Gómez',
                'image' => 'assets/images/modelos_eclat/francisco.jpg',
                'altura' => 1.80,
                'bust' => 100,
                'cintura' => 78,
                'zapato' => 43,
                'vestido' => 0, // idem Lucas
                'tamano' => "M",
                'ojos' => 'Ambar',
                'cabello' => 'Negros',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1998')->format('Y-m-d'),
                'ubicacion' => 'Neuquén, Neuquén, Argentina',
                'instagram' => 'francis_oficial',
                'description' => 'Traços fortes, olhar profundo e presença dramática. Excelente para editoriais de moda em preto e branco, campanhas conceituais, moda alternativa e publicidade de impacto artístico. Cabelos ondulados, olhar penetrante, presença forte em preto e branco. Intensidade, mistério e profundidade artística. Ideal para marcas que buscam expressividade dramática e imagens memoráveis.',
                'campana' => 'Editorial conceitual, moda alternativa, campanhas de alta costura, publicidade artística.',
            ],
            [
                'name' => 'Valentina Rossì',
                'image' => 'assets/images/modelos_eclat/valentina.jpg',
                'altura' => 1.75,
                'bust' => 86,
                'cintura' => 62,
                'zapato' => 38,
                'vestido' => 36,
                'tamano' => "M",
                'ojos' => 'Castaños Claros',
                'cabello' => 'Castaños',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1997')->format('Y-m-d'),
                'ubicacion' => 'Rosario, Santa Fe, Argentina',
                'instagram' => 'its_rossi',
                'description' => 'Traços fortes, olhar profundo e presença dramática. Excelente para editoriais de moda em preto e branco, campanhas conceituais, moda alternativa e publicidade de impacto artístico. Líneas fluidas, corte asimétrico con abertura lateral que resalta movimiento y feminidad. Confianza, sensualidad discreta y poder femenino. Impacta por el brillo y dramatismo del vestido en contraste con la pose dinámica.',
                'campana' => 'Moda de lujo, editoriales de alta costura, marcas premium de gala.',
            ],
            [
                'name' => 'Jose Bianchi',
                'image' => 'assets/images/modelos_eclat/jose.jpg',
                'altura' => 1.90,
                'bust' => 100,
                'cintura' => 80,
                'zapato' => 44,
                'vestido' => 0,
                'tamano' => "G",
                'ojos' => 'Morones',
                'cabello' => 'Castaño Oscuro',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1996')->format('Y-m-d'),
                'ubicacion' => 'Buenos Aires, Capital Federal, Argentina',
                'instagram' => 'bianchi_jose',
                'description' => 'Traços fortes, olhar profundo e presença dramática. Excelente para editoriais de moda em preto e branco, campanhas conceituais, moda alternativa e publicidade de impacto artístico. Estilo atemporal, sonrisa fresca y natural. Cercanía, autenticidad y optimismo juvenil. Su expresión abierta y espontánea genera conexión inmediata.',
                'campana' => 'Moda urbana, lifestyle, marcas de ropa masculina y fragancias.',
            ],
            [
                'name' => 'Camila Sánchez',
                'image' => 'assets/images/modelos_eclat/camila.jpg',
                'altura' => 1.80,
                'bust' => 88,
                'cintura' => 63,
                'zapato' => 39,
                'vestido' => 38,
                'tamano' => "M",
                'ojos' => 'Negros',
                'cabello' => 'Negros',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1995')->format('Y-m-d'),
                'ubicacion' => 'Bahía Blanca, Buenos Aires, Argentina',
                'instagram' => 'camysanchez',
                'description' => 'Traços fortes, olhar profundo e presença dramática. Excelente para editoriais de moda em preto e branco, campanhas conceituais, moda alternativa e publicidade de impacto artístico. Mirada cálida y fuerte, cuerpo marcante y simple, postura elegante. Valentía, seguridad y magnetismo. La intensidad del animal print enmarcado por el fondo natural potencia la fuerza de su mirada.',
                'campana' => 'Alta moda, editoriales de lujo, marcas con actitud irreverente.',
            ],
            [
                'name' => 'Dylan Rodríguez',
                'image' => 'assets/images/modelos_eclat/dylan.jpg',
                'altura' => 1.95,
                'bust' => 105,
                'cintura' => 82,
                'zapato' => 45,
                'vestido' => 0,
                'tamano' => "M",
                'ojos' => 'Negros',
                'cabello' => 'Negros',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1996')->format('Y-m-d'),
                'ubicacion' => 'Buenos Aires, Capital Federal, Argentina',
                'instagram' => 'im_dylan_of',
                'description' => 'Traços fortes, olhar profundo e presença dramática. Excelente para editoriais de moda em preto e branco, campanhas conceituais, moda alternativa e publicidad de impacto artístico. Frescura, modernidad y un aire introspectivo. Silueta amplia, monocromía, actitud relajada. La pureza del look monocromático transmite calma y sofisticación.',
                'campana' => 'Moda urbana, colecciones cápsula de streetwear, marcas sostenibles.',
            ],
            [
                'name' => 'Sofia Ricci',
                'image' => 'assets/images/modelos_eclat/sofia.jpg',
                'altura' => 1.90,
                'bust' => 90,
                'cintura' => 65,
                'zapato' => 40,
                'vestido' => 38,
                'tamano' => "P",
                'ojos' => 'Azules',
                'cabello' => 'Rubio',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1994')->format('Y-m-d'),
                'ubicacion' => 'Mendoza, Mendoza, Argentina',
                'instagram' => 'sofii_ricci',
                'description' => 'Traços fortes, olhar profundo e presença dramática. Excelente para editoriais de moda em preto e branco, campanhas conceituais, moda alternativa e publicidad de impacto artístico. Cuerpo en formato escultural intenso, miradas marcantes, actitud fuerte y determinada. Misticismo, audacia artística y magnetismo escénico. El dramatismo del diseño junto al gesto coreográfico la convierten en un ícono visual.',
                'campana' => 'Pasarelas de alta moda, editoriales conceptuales, marcas exclusivas.',
            ],
            [
                'name' => 'Emanuel Hernández',
                'image' => 'assets/images/modelos_eclat/emanuel.jpg',
                'altura' => 1.85,
                'bust' => 102,
                'cintura' => 80,
                'zapato' => 43,
                'vestido' => 0,
                'tamano' => "M",
                'ojos' => 'Negros',
                'cabello' => 'Rubio',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1997')->format('Y-m-d'),
                'ubicacion' => 'Quilmes, Buenos Aires, Argentina',
                'instagram' => 'ema_nandez',
                'description' => 'Traços fortes, olhar profundo e presença dramática. Excelente para editoriais de moda em preto e branco, campañas conceptuales, moda alternativa y publicidad de impacto artístico. Mirada intensa, tatuaje visible, estética en blanco y negro que realza fuerza emocional. Profundidad, misterio y un aire provocador. Su expresión desafiante y el contraste en blanco y negro generan una narrativa poderosa.',
                'campana' => 'Moda alternativa, campañas de joyería, marcas de identidad fuerte.',
            ]
        ]);
    }
}
