<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class ModelosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('modelos')->insert([
            [
                'name' => 'Andressa Viena',
                'image' => 'assets/images/modelos_eclat/andressa.jpg',
                'altura' => 1.85,
                'bust' => 85,
                'cintura' => 60,
                'zapato' => 35,
                'vestido' => 36,
                'tamano' => 'M',
                'ojos' => 'Negros',
                'cabello' => 'Negro',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1997')->format('Y-m-d'),
                'ubicacion' => 'Buenos Aires, Capital Federal, Argentina',
                'instagram' => 'andressa_oficial',
                'description' => 'Elegância contemporânea com beleza clássica. Pele impecável, traços finos e olhar confiante. Ideal para campanhas de beleza de luxo, maquiagem e editoriais sofisticados. Pele luminosa impecável, olhos expressivos, lábios definidos, rosto harmônico. Confiança, sofisticação e magnetismo. Capacidade de sustentar closes intensos com impacto imediato.',
                'campana' => 'Belleza de lujo, cuidado de la piel premium, maquillaje de alta costura, joyería y editoriales de moda conceptual.',
            ],
            [
                'name' => 'Juan Díaz',
                'image' => 'assets/images/modelos_eclat/juan.jpg',
                'altura' => 1.85,
                'bust' => 90,
                'cintura' => 75,
                'zapato' => 40,
                'vestido' => 47,
                'tamano' => 'G',
                'ojos' => 'Verde Oliva',
                'cabello' => 'Castaño Oscuro',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '29/09/1999')->format('Y-m-d'),
                'ubicacion' => 'Rawson, Chubut, Argentina',
                'instagram' => 'diazjuani',
                'description' => 'Perfil serio, presencia magnética y postura refinada. Combina perfectamente con moda masculina premium, trajes, campañas de estilo de vida urbano y editoriales cosmopolitas. Mandíbula definida, barba sutil, complexión atlética, mirada contemplativa. Determinación, encanto discreto e inteligencia. Perfecto para representar al hombre cosmopolita, centrado y contemporáneo.',
                'campana' => 'Moda masculina de alta gama, trajes, sastrería, campañas de relojes y estilo de vida urbano sofisticado.',
            ],
            [
                'name' => 'Paula Olegari',
                'image' => 'assets/images/modelos_eclat/paula.jpg',
                'altura' => 1.78,
                'bust' => 85,
                'cintura' => 60,
                'zapato' => 39,
                'vestido' => 36,
                'tamano' => 'M',
                'ojos' => 'Ambar',
                'cabello' => 'Rubio Oscuro',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '24/02/1998')->format('Y-m-d'),
                'ubicacion' => 'Rosario, Santa Fe, Argentina',
                'instagram' => 'imolegari',
                'description' => 'Postura delicada, expresión introspectiva y estilo limpio. Representa autenticidad y ligereza, excelente para editoriales minimalistas, marcas de moda sostenible y campañas íntimas. Cabello rizado suelto, piel clara natural, silueta elegante. Delicadeza, autenticidad e introspección. Capacidad para transmitir pureza y autenticidad en entornos sencillos o editoriales íntimos.',
                'campana' =>  'Moda sustentável, editoriais de lifestyle clean, marcas conceituais, beleza natural.',
            ],
            [
                'name' => 'Lucas Fernandez',
                'image' => 'assets/images/modelos_eclat/lucas.jpg',
                'ojos' => 'Negros',
                'altura' => 1.88,
                'bust' => 95,
                'cintura' => 75,
                'zapato' => 42,
                'vestido' => 0, // não aplicável em homem, pode deixar 0 ou null
                'tamano' => "P",
                'cabello' => 'Castaño',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '20/10/2000')->format('Y-m-d'),
                'ubicacion' => 'Córdoba, Córdoba, Argentina',
                'instagram' => 'feerr_luc',
                'description' => 'Actitud desenfadada, look urbano y presencia cool. Ideal para campañas juveniles, moda alternativa, editoriales de street style y publicidad dirigida al público creativo. Postura relajada, cabello voluminoso, gafas futuristas, actitud cool. Libertad, audacia y vanguardia. Representa al joven contemporáneo, irreverente y conectado con la cultura pop.',
                'campana' => 'Moda urbana, editoriales de tendencias juveniles, estilo callejero, marcas alternativas y campañas digitales.',
            ],
            [
                'name' => 'Victoria Bithencurt',
                'image' => 'assets/images/modelos_eclat/victoria.jpg',
                'altura' => 1.80,
                'bust' => 87,
                'cintura' => 62,
                'zapato' => 38,
                'vestido' => 36,
                'tamano' => "P",
                'ojos' => 'Verdes',
                'cabello' => 'Pelirroja',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '14/11/1996')->format('Y-m-d'),
                'ubicacion' => 'Olivos, Buenos Aires, Argentina',
                'instagram' => 'vic_bithencurt',
                'description' => 'Mirada dulce, sonrisa suave y carisma natural. La estética ligera y colorida combina con campañas de moda femenina, verano, estilo de vida tropical y belleza natural. Cabello largo pelirrojo, ojos claros, sonrisa sutil, piel radiante. Alegría, calidez humana y cercanía. Brillo natural que conecta fácilmente con el público, transmitiendo frescura y accesibilidad.',
                'campana' => 'Moda femenina colorida, estilo de vida tropical, campañas de verano, cosméticos y moda casual.',
            ],
            [
                'name' => 'Francisco Gómez',
                'image' => 'assets/images/modelos_eclat/francisco.jpg',
                'altura' => 1.80,
                'bust' => 100,
                'cintura' => 78,
                'zapato' => 43,
                'vestido' => 0, // idem Lucas
                'tamano' => "M",
                'ojos' => 'Ambar',
                'cabello' => 'Negros',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1998')->format('Y-m-d'),
                'ubicacion' => 'Neuquén, Neuquén, Argentina',
                'instagram' => 'francis_oficial',
                'description' => 'Rasgos marcados, mirada profunda y presencia dramática. Excelente para editoriales de moda en blanco y negro, campañas conceptuales, moda alternativa y publicidad de impacto artístico. Cabello ondulado, mirada penetrante, fuerte presencia en blanco y negro. Intensidad, misterio y profundidad artística. Ideal para marcas que buscan expresividad dramática e imágenes memorables.',
                'campana' => 'Editorial conceptual, moda alternativa, campañas de alta costura, publicidad artística.',
            ],
            [
                'name' => 'Valentina Rossì',
                'image' => 'assets/images/modelos_eclat/valentina.jpg',
                'altura' => 1.75,
                'bust' => 86,
                'cintura' => 62,
                'zapato' => 38,
                'vestido' => 36,
                'tamano' => "M",
                'ojos' => 'Castaños Claros',
                'cabello' => 'Castaños',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1997')->format('Y-m-d'),
                'ubicacion' => 'Rosario, Santa Fe, Argentina',
                'instagram' => 'its_rossi',
                'description' => 'Rasgos marcados, mirada profunda y presencia dramática. Excelente para editoriales de moda en blanco y negro, campañas conceptuales, moda alternativa y publicidad de impacto artístico. Líneas fluidas, corte asimétrico con abertura lateral que resalta el movimiento y la feminidad. Confianza, sensualidad discreta y poder femenino. Impacta por el brillo y dramatismo del vestido en contraste con la pose dinámica.',
                'campana' => 'Moda de lujo, editoriales de alta costura, marcas premium de gala.',
            ],
            [
                'name' => 'Jose Bianchi',
                'image' => 'assets/images/modelos_eclat/jose.jpg',
                'altura' => 1.90,
                'bust' => 100,
                'cintura' => 80,
                'zapato' => 44,
                'vestido' => 0,
                'tamano' => "G",
                'ojos' => 'Morones',
                'cabello' => 'Castaño Oscuro',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1996')->format('Y-m-d'),
                'ubicacion' => 'Buenos Aires, Capital Federal, Argentina',
                'instagram' => 'bianchi_jose',
                'description' => 'Rasgos marcados, mirada profunda y presencia dramática. Excelente para editoriales de moda en blanco y negro, campañas conceptuales, moda alternativa y publicidad con impacto artístico. Estilo atemporal, sonrisa fresca y natural. Accesibilidad, autenticidad y optimismo juvenil. Su expresión abierta y espontánea crea una conexión inmediata.',
                'camapana' => 'Moda urbana, estilo de vida, marcas de ropa masculina y fragancias.',
            ],
            [
                'name' => 'Camila Sánchez',
                'image' => 'assets/images/modelos_eclat/camila.jpg',
                'altura' => 1.80,
                'bust' => 88,
                'cintura' => 63,
                'zapato' => 39,
                'vestido' => 38,
                'tamano' => "M",
                'ojos' => 'Negros',
                'cabello' => 'Negros',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1995')->format('Y-m-d'),
                'ubicacion' => 'Bahía Blanca, Buenos Aires, Argentina',
                'instagram' => 'camysanchez',
                'description' => 'Rasgos marcados, mirada profunda y presencia dramática. Excelente para editoriales de moda en blanco y negro, campañas conceptuales, moda alternativa y publicidad de impacto artístico. Mirada cálida y fuerte, cuerpo llamativo y sencillo, postura elegante. Valentía, seguridad y magnetismo. La intensidad del estampado animal enmarcado por el fondo natural potencia la fuerza de su mirada.',
                'campana' => 'Alta costura, editoriales de lujo, marcas con una actitud irreverente.',
            ],
            [
                'name' => 'Dylan Rodríguez',
                'image' => 'assets/images/modelos_eclat/dylan.jpg',
                'altura' => 1.95,
                'bust' => 105,
                'cintura' => 82,
                'zapato' => 45,
                'vestido' => 0,
                'tamano' => "M",
                'ojos' => 'Negros',
                'cabello' => 'Negros',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1996')->format('Y-m-d'),
                'ubicacion' => 'Buenos Aires, Capital Federal, Argentina',
                'instagram' => 'im_dylan_of',
                'description' => 'Rasgos marcados, mirada profunda y presencia dramática. Excelente para editoriales de moda en blanco y negro, campañas conceptuales, moda alternativa y publicidad de impacto artístico. Frescura, modernidad y un aire introspectivo. Silueta amplia, monocromía, actitud relajada. La pureza del look monocromático transmite calma y sofisticación.',
                'campana' => 'Moda urbana, colecciones cápsula de streetwear, marcas sostenibles.',
            ],
            [
                'name' => 'Sofia Ricci',
                'image' => 'assets/images/modelos_eclat/sofia.jpg',
                'altura' => 1.90,
                'bust' => 90,
                'cintura' => 65,
                'zapato' => 40,
                'vestido' => 38,
                'tamano' => "P",
                'ojos' => 'Azules',
                'cabello' => 'Rubio',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1994')->format('Y-m-d'),
                'ubicacion' => 'Mendoza, Mendoza, Argentina',
                'instagram' => 'sofii_ricci',
                'description' => 'Rasgos marcados, mirada profunda y presencia dramática. Excelente para editoriales de moda en blanco y negro, campañas conceptuales, moda alternativa y publicidad con impacto artístico. Un cuerpo intensamente escultural, una apariencia llamativa, una actitud fuerte y decidida. Misticismo, audacia artística y magnetismo escénico. El dramatismo del diseño, junto con los gestos coreografiados, la convierten en un ícono visual.',
                'campana' => 'Pasarelas de alta costura, editoriales conceptuales, marcas exclusivas.',
            ],
            [
                'name' => 'Emanuel Hernández',
                'image' => 'assets/images/modelos_eclat/emanuel.jpg',
                'altura' => 1.85,
                'bust' => 102,
                'cintura' => 80,
                'zapato' => 43,
                'vestido' => 0,
                'tamano' => "M",
                'ojos' => 'Negros',
                'cabello' => 'Rubio',
                'fecha_nacimiento' => \Carbon\Carbon::createFromFormat('d/m/Y', '10/04/1997')->format('Y-m-d'),
                'ubicacion' => 'Quilmes, Buenos Aires, Argentina',
                'instagram' => 'ema_nandez',
                'description' => 'Rasgos fuertes, mirada profunda y presencia dramática. Excelente para editoriales de moda en blanco y negro, campañas conceptuales, moda alternativa y publicidad de impacto artístico. Mirada intensa, tatuaje visible, estética en blanco y negro que realza la fuerza emocional. Profundidad, misterio y un aire provocador. Su expresión desafiante y el contraste en blanco y negro generan una narrativa poderosa.',
                'campana' => 'Alternative fashion, jewelry campaigns, strong identity brands.',
            ]
        ]);
    }
}
